name: Deploy Docs

on:
  push:
    branches:
      - main
      - work

jobs:
  deploy-gh-pages:
    name: Deploy docs to gh pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:vite-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
          single-commit: true
