name: Test

on:
  push:
    branches:
      - main
      - work
  pull_request:
    branches:
      - main

jobs:
  linter-and-unit:
    name: Linter and Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Linter test
        run: |
          pnpm run lint:check
          pnpm run lint:md

      - name: Unit test
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run test

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
